import os
import sys
import json
import argparse
import datetime
from nwg_displays.tools import hyprctl, save_list_to_text_file


def get_config_dir():
    xdg_config_home = os.getenv("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
    return os.path.join(xdg_config_home, "nwg-displays")


def apply_profile_json(profile_data, outputs_path):
    displays = profile_data["displays"]
    config = profile_data["config"]
    use_desc = config.get("use-desc", False)

    now = datetime.datetime.now()
    lines = [
        "# Generated by nwg-displays (Profile Loader) on {} at {}. Do not edit manually.\n".format(
            datetime.datetime.strftime(now, "%Y-%m-%d"),
            datetime.datetime.strftime(now, "%H:%M:%S"),
        )
    ]

    if os.getenv("HYPRLAND_INSTANCE_SIGNATURE"):
        transforms = {
            "normal": 0,
            "90": 1,
            "180": 2,
            "270": 3,
            "flipped": 4,
            "flipped-90": 5,
            "flipped-180": 6,
            "flipped-270": 7,
        }

        print(f"[Profile] Applying {len(displays)} displays for Hyprland...")

        for d in displays:
            if not use_desc:
                name = d["name"]
            else:
                desc_safe = d["description"].replace("#", "##")
                name = f"desc:{desc_safe}"

            if not d["active"]:
                lines.append(f"monitor={name},disable")
                hyprctl(f"dispatch dpms off {d['name']}")
                continue

            # Format: monitor=name,resolution@refresh,position,scale
            line = "monitor={},{}x{}@{},{}x{},{}".format(
                name,
                d["physical_width"],
                d["physical_height"],
                d["refresh"],
                d["x"],
                d["y"],
                d["scale"],
            )

            if d.get("mirror"):
                line += ",mirror,{}".format(d["mirror"])

            if d.get("ten_bit"):
                line += ",bitdepth,10"

            lines.append(line)

            if d["transform"] != "normal":
                t_code = transforms.get(d["transform"], 0)
                lines.append(f"monitor={name},transform,{t_code}")

            cmd = "on" if d["dpms"] else "off"
            hyprctl(f"dispatch dpms {cmd} {d['name']}")

        save_list_to_text_file(lines, outputs_path)
        hyprctl("reload")

        if "wallpapers" in profile_data:
            print("[Profile] Applying wallpapers...")
            for monitor, path in profile_data["wallpapers"].items():
                os.system(f"swww img -o {monitor} {path} --transition-type simple")

    elif os.getenv("SWAYSOCK"):
        from i3ipc import Connection

        cmds = []
        for d in displays:
            name = d["description"] if use_desc else d["name"]
            if not d["active"]:
                cmds.append(f'output "{name}" disable')
                continue

            cmd = 'output "{}"'.format(name)
            custom = "--custom" if d["custom_mode"] else ""
            cmd += " mode {} {}x{}@{}Hz".format(
                custom, d["physical_width"], d["physical_height"], d["refresh"]
            )
            cmd += " pos {} {}".format(d["x"], d["y"])
            cmd += " transform {}".format(d["transform"])
            cmd += " scale {}".format(d["scale"])

            if d.get("scale_filter"):
                cmd += " scale_filter {}".format(d["scale_filter"])

            a_s = "on" if d["adaptive_sync"] else "off"
            cmd += " adaptive_sync {}".format(a_s)

            dpms = "on" if d["dpms"] else "off"
            cmd += " dpms {}".format(dpms)
            cmds.append(cmd)

        i3 = Connection()
        for cmd in cmds:
            i3.command(cmd)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Load nwg-displays profile directly.")
    parser.add_argument(
        "-p", "--profile", type=str, required=True, help="Name of the profile to load"
    )
    parser.add_argument(
        "-c", "--config", type=str, help="Path to monitors.conf override"
    )

    args = parser.parse_args()

    config_dir = get_config_dir()

    profile_path = os.path.join(config_dir, "profiles", f"{args.profile}.json")

    if args.config:
        outputs_path = args.config
    else:
        outputs_path = os.path.join(
            os.path.expanduser("~/.config/hypr/"), "monitors.conf"
        )

    if not os.path.isfile(profile_path):
        print(f"Error: Profile file not found at {profile_path}")
        sys.exit(1)

    try:
        with open(profile_path, "r") as f:
            profile_data = json.load(f)

        print(f"Loading profile: '{args.profile}'")
        apply_profile_json(profile_data, outputs_path)
        print("Done.")

    except json.JSONDecodeError:
        print(f"Error: Failed to parse {profile_path}. Invalid JSON.")
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        sys.exit(1)
